var rule = {
  title: "NY影院",
  host: "https://www.nycvod.com",
  homeUrl: "https://nycvod.com/vodshow/30--------fypage---.html",
  class_name: "电视剧&短剧",
  class_url: "30&50",
  url: "/vodshow/fyclass--------fypage---.html",
  detailUrl: "/voddetail/fyid.html",
  推荐: ".public-list-box;a&&title;.lazy&&data-src;.public-list-prb&&Text;a&&href",
  double: false,
  searchable: 0,
  quickSearch: 0,
  headers: { "User-Agent": "MOBILE_UA" },
  filterable: 0, //是否启用分类筛选,
  一级: 'js:let body=input.split("#")[1];let t=Math.round(new Date/1e3).toString();let key=md5("DS"+t+"DCC147D11943AF75");let url=input.split("#")[0];body=body+"&time="+t+"&key="+key;print(body);fetch_params.body=body;let html=post(url,fetch_params);let data=JSON.parse(html);VODS=data.list.map(function(it){it.vod_pic=urljoin2(input.split("/i")[0],it.vod_pic);return it});',
  二级: {
    title: ".slide-info-title&&Text;.slide-info:eq(3)--strong&&Text",
    img: ".detail-pic&&data-original",
    desc: ".fraction&&Text;.slide-info-remarks:eq(1)&&Text;.slide-info-remarks:eq(2)&&Text;.slide-info:eq(2)--strong&&Text;.slide-info:eq(1)--strong&&Text",
    content: "#height_limit&&Text",
    tabs: ".anthology.wow.fadeInUp.animated&&.swiper-wrapper&&a",
    tab_text: ".swiper-slide&&Text",
    lists: ".anthology-list-box:eq(#id) li",
  },
  搜索: "json:list;name;pic;;id",
};
